#!/bin/bash

export DD_LOGS_INJECTION=$DD_LOGS_INJECTION
export DD_SERVICE=$DD_SERVICE
export DD_ENV=$DD_ENV
export DD_VERSION=$DD_VERSION
export DD_GIT_REPOSITORY_URL=github.com/ccdaniele/se-ssi-playground
export DD_VERSION=$DD_VERSION
export NODE_OPTIONS=$NODE_OPTIONS
export DD_TRACE_DEBUG=$DD_TRACE_DEBUG
export DD_GIT_COMMIT_SHA="525a1f1b5875367e7c12b2423527d221e1aa533c"
next dev 
